---
title: "Prediction of aboveground biomass (AGB) in Inner Mongolia grasslands, China"
author: "Jincheng Yao_#77521491, Jinlin Ning_#15714006"
subtitle: EAS 648 Final project
output:
  html_document:
    highlight: tango
    theme: cerulean
  pdf_document: default
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
#code chunk to put in default settings, like whether other code chunks run/show messages
knitr::opts_chunk$set(echo = TRUE, 
                      messages = FALSE)

# Set so that long lines in R will be wrapped:
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=80), tidy=TRUE)
#note may need to install and load package "formatR" for this to run. 

options (width = 80)

```

```{r 1}
library(shiny)
library(sf)
library(mapview)
library(leaflet)
library(ggplot2)
library(dplyr)


# points data
data <- read.csv("data/csv/attributes.csv")

data$Region <- dplyr::recode(data$Region,
                             "H" = "Hulunbuir",
                             "X" = "Xilin Gol")

pts_full <- st_as_sf(
  data,
  coords = c("Longtitude", "Latitude"),
  crs = 4326,
  remove = FALSE
)

# data source
source_map <- list(
  "UAV" = "UAV",
  "Landsat-8" = "L8",
  "MODIS" = "MODIS"
)
vi_list <- c("NDVI", "KNDVI", "EVI", "OSAVI")

# research area
inner_mongolia <- st_read("data/raster/inner_mongolia.shp")
```



```{r 2}
# ui
ui <- fluidPage(

  titlePanel("Prediction of Aboveground Biomass (AGB) in Inner Mongolia Grasslands, China"),

  sidebarLayout(

    sidebarPanel(

      h4("Data Used for Modeling"),
      radioButtons("year", "Year:", 
                   choices = c("2021", "2022", "All"), 
                   selected = "All"),
      radioButtons("region", "Region:", 
                   choices = c("Hulunbuir", "Xilin Gol", "All"), 
                   selected = "All"),
      radioButtons("source", "Data Level:", 
                   choices = c("UAV", "Landsat-8", "MODIS"), 
                   selected = "MODIS"),
      selectInput("vi", "Vegetation Index:", 
                  choices = c("NDVI", "KNDVI", "OSAVI", "EVI"), 
                  selected = "NDVI")
    ),

    mainPanel(
      # Map (top)
      fluidRow(
        column(
          width = 12,
          leafletOutput("map", height = "500px")
        )
      ),

      fluidRow(
        # scatter plot
        column(
          width = 6,
          plotOutput("scatter", height = "300px")
        ),

        # statistics summary
        column(
          width = 6,
          tableOutput("stats")
        )
      )
    )
  )
)
```

```{r 3}
# Defining the column name
vi_map <- list("UAV" = list("NDVI" = "NDVIUAV",
                            "KNDVI" = "KNDVIUAV",
                            "EVI" = "EVIUAV",
                            "OSAVI" = "OSAVIUAV"),
               "Landsat-8" = list("NDVI" = "NDVIL8",
                                  "KNDVI" = "KNDVIL8",
                                  "EVI" = "EVIL8",
                                  "OSAVI" = "OSAVIL8"),
               "MODIS" = list("NDVI" = "NDVIMODIS",
                              "KNDVI" = "KNDVIMODIS",
                              "EVI" = "EVIMODIS",
                              "OSAVI" = "OSAVIMODIS"))



# service
server <- function(input, output, session) {

  # dealing with VI name
  active_vi_field <- reactive({
    if (input$vi == "All") return(NULL)
    vi_map[[input$source]][[input$vi]]
    })

  # filter data
  filtered_data <- reactive({
    df <- pts_full
    if (input$year != "All") df <- df %>% filter(Year == input$year)
    if (input$region != "All") df <- df %>% filter(Region == input$region)
    vi_col <- active_vi_field()
    
    if (!is.null(vi_col) && vi_col %in% names(df)){
      df <- df %>% filter(!is.na(.data[[vi_col]]))
      }
    df
    })

  # mapping
  output$map <- renderLeaflet({

    df <- filtered_data()
    vi_col <- active_vi_field()

    pal <- colorNumeric("YlGn", df$AGB)
    
    if (is.null(vi_col) || !(vi_col %in% names(df))) {
      popup_txt <- paste0("Point: ", df$point, "<br>",
                          "AGB: ", round(df$AGB, 2), "<br>",
                          "VI: All<br>",
                          "Source: ", input$source)
      } else {
        popup_txt <- paste0("Point: ", df$point, "<br>",
                            "AGB: ", round(df$AGB, 2), "<br>",
                            input$vi, ": ", round(df[[vi_col]], 3), "<br>",
                            "Source: ", input$source)
        }

    leaflet(df) %>% 
      addTiles() %>% 
      addPolygons(data = inner_mongolia, 
                  fill = FALSE, 
                  color = "black", 
                  weight = 2) %>% 
      addCircleMarkers(lng = ~Longtitude, 
                       lat = ~Latitude, 
                       radius = 5, 
                       fillColor = ~pal(AGB), 
                       fillOpacity = 0.8, 
                       stroke = TRUE, 
                       color = "white", 
                       popup = popup_txt)
  })

  # scatter plot
  output$scatter <- renderPlot({
    req(input$vi != "All")
    df <- filtered_data()
    vi_col <- active_vi_field()
    req(vi_col %in% names(df))
    ggplot(df, aes(x = .data[[vi_col]], y = AGB)) +
      geom_point(alpha = 0.7, color = "darkgreen") +
      geom_smooth(method = "lm") +
      theme_bw() +
      labs(title = paste("AGB ~", input$vi, "(", input$source, ")"))
    })

  # statistic
  output$stats <- renderTable({
    req(input$vi != "All")
    df <- filtered_data()
    vi_col <- active_vi_field()
    req(vi_col %in% names(df))
    fit <- lm(as.formula(paste("AGB ~", vi_col)), data = df)
    data.frame(
      description = c("intercept", "slope", "R square", "RMSE", "n"),
      value = c(coef(fit)[1],
                coef(fit)[2],
                summary(fit)$r.squared,
                sqrt(mean(fit$residuals^2)),
                nrow(df))
      )
  })
}


```

```{r 4}
# run
shinyApp(ui, server)
```